#!/bin/bash

PATHFILE=$1

NLINES=$(cat $PATHFILE | wc -l)
NEVENTS=$(echo $(($NLINES/256)))

echo "********************************************************"
echo "         Pre toolchain"
echo "********************************************************"
echo "  "
echo " File: '$PATHFILE'"
echo " Events: '$NEVENTS'"
echo "  "
echo " Modifying the following configfiles:"
echo "  - 'configfiles/LAPPDana/ConfigASCIIReadIn'"
echo "  - 'configfiles/LAPPDana/ToolChainConfig'"
echo "  "
echo "********************************************************"

# Replacing the numbers if events in ToolChainConfig
awk '{ if (NR == 22) print "Inline '$NEVENTS' ## number of Execute steps in program, -1 infinite loop that is ended by user"; else print $0}' configfiles/LAPPDana/ToolChainConfig > configfiles/LAPPDana/output_file.txt
rm -f configfiles/LAPPDana/ToolChainConfig
mv configfiles/LAPPDana/output_file.txt configfiles/LAPPDana/ToolChainConfig

# Replacing the input path
awk '{ if (NR == 18) print "PSECinputfile '$PATHFILE'"; else print $0}' configfiles/LAPPDana/ConfigASCIIReadIn > configfiles/LAPPDana/output_file2.txt
rm -f configfiles/LAPPDana/ConfigASCIIReadIn
mv configfiles/LAPPDana/output_file2.txt configfiles/LAPPDana/ConfigASCIIReadIn

echo "Running ./Analyse configfiles/LAPPDana/ToolChainConfig"
./Analyse configfiles/LAPPDana/ToolChainConfig

echo "$(date)   $NEVENTS        $PATHFILE" >> RunHistory.log
